language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-23
    - extra-android-support
    - extra-android-m2repository

script:
    - ./gradlew --info test
